export { ReactComponent as Terbaru } from './terbaru.svg'
export { ReactComponent as Terlama } from './terlama.svg'
export { ReactComponent as AZ } from './a-z.svg'
export { ReactComponent as ZA } from './z-a.svg'
export { ReactComponent as BelumSelesai } from './belum-selesai.svg'
export { ReactComponent as Selected } from './selected.svg'
